export const TrackElemType = {
  flat: 0,
  endStation: 1,
  beginStation: 2,
  middleStation: 3,
  up25: 4,
  up60: 5,
  flatToUp25: 6,
  up25ToUp60: 7,
  up60ToUp25: 8,
  up25ToFlat: 9,
  down25: 10,
  down60: 11,
  flatToDown25: 12,
  down25ToDown60: 13,
  down60ToDown25: 14,
  down25ToFlat: 15,
  leftQuarterTurn5Tiles: 16,
  rightQuarterTurn5Tiles: 17,
  flatToLeftBank: 18,
  flatToRightBank: 19,
  leftBankToFlat: 20,
  rightBankToFlat: 21,
  bankedLeftQuarterTurn5Tiles: 22,
  bankedRightQuarterTurn5Tiles: 23,
  leftBank: 32,
  rightBank: 33,
  sBendLeft: 38,
  sBendRight: 39,
  leftVerticalLoop: 40,
  rightVerticalLoop: 41,
  leftQuarterTurn3Tiles: 42,
  rightQuarterTurn3Tiles: 43,
  leftBankedQuarterTurn3Tiles: 44,
  rightBankedQuarterTurn3Tiles: 45,
  leftQuarterTurn1Tile: 50,
  rightQuarterTurn1Tile: 51,
  halfLoopUp: 56,
  halfLoopDown: 57,
  leftCorkscrewUp: 58,
  rightCorkscrewUp: 59,
  leftCorkscrewDown: 60,
  rightCorkscrewDown: 61,
  flatToUp60: 62,
  up60ToFlat: 63,
  flatToDown60: 64,
  down60ToFlat: 65,
  leftHalfBankedHelixUpSmall: 87,
  rightHalfBankedHelixUpSmall: 88,
  leftHalfBankedHelixDownSmall: 89,
  rightHalfBankedHelixDownSmall: 90,
  leftHalfBankedHelixUpLarge: 91,
  rightHalfBankedHelixUpLarge: 92,
  leftHalfBankedHelixDownLarge: 93,
  rightHalfBankedHelixDownLarge: 94,
  brakes: 99,
  booster: 100,
  leftQuarterBankedHelixLargeUp: 102,
  rightQuarterBankedHelixLargeUp: 103,
  leftQuarterBankedHelixLargeDown: 104,
  rightQuarterBankedHelixLargeDown: 105,
  leftQuarterHelixLargeUp: 106,
  rightQuarterHelixLargeUp: 107,
  leftQuarterHelixLargeDown: 108,
  rightQuarterHelixLargeDown: 109,
  cableLiftHill: 123,
  up90: 126,
  down90: 127,
  up60ToUp90: 128,
  down90ToDown60: 129,
  up90ToUp60: 130,
  down60ToDown90: 131,
  brakeForDrop: 132,
  leftBarrelRollUpToDown: 174,
  rightBarrelRollUpToDown: 175,
  leftBarrelRollDownToUp: 176,
  rightBarrelRollDownToUp: 177,
  poweredLift: 182,
  leftLargeHalfLoopUp: 183,
  rightLargeHalfLoopUp: 184,
  leftLargeHalfLoopDown: 185,
  rightLargeHalfLoopDown: 186,
  blockBrakes: 216,
  leftBankedQuarterTurn3TileUp25: 217,
  rightBankedQuarterTurn3TileUp25: 218,
  leftBankedQuarterTurn3TileDown25: 219,
  rightBankedQuarterTurn3TileDown25: 220,
  leftBankedQuarterTurn5TileUp25: 221,
  rightBankedQuarterTurn5TileUp25: 222,
  leftBankedQuarterTurn5TileDown25: 223,
  rightBankedQuarterTurn5TileDown25: 224,
  up25LeftBanked: 110,
  up25RightBanked: 111,
  down25LeftBanked: 115,
  down25RightBanked: 116,
  leftLargeCorkscrewUp: 267,
  rightLargeCorkscrewUp: 268,
  leftLargeCorkscrewDown: 269,
  rightLargeCorkscrewDown: 270,
  leftMediumHalfLoopUp: 271,
  rightMediumHalfLoopUp: 272,
  leftMediumHalfLoopDown: 273,
  rightMediumHalfLoopDown: 274,
  leftZeroGRollUp: 275,
  rightZeroGRollUp: 276,
  leftZeroGRollDown: 277,
  rightZeroGRollDown: 278,
  leftLargeZeroGRollUp: 279,
  rightLargeZeroGRollUp: 280,
  leftLargeZeroGRollDown: 281,
  rightLargeZeroGRollDown: 282,
  multiDimInvertedFlatToDown90QuarterLoop: 206,
  up90ToInvertedFlatQuarterLoop: 207,
  invertedFlatToDown90QuarterLoop: 208,
  leftEighthDiveLoopUpToOrthogonal: 345,
  rightEighthDiveLoopUpToOrthogonal: 346,
  leftEighthDiveLoopDownToDiag: 347,
  rightEighthDiveLoopDownToDiag: 348
} as const;

export type TrackElementName = keyof typeof TrackElemType;

export const INVERSION_ELEMENT_IDS = new Set<number>([
  TrackElemType.leftVerticalLoop,
  TrackElemType.rightVerticalLoop,
  TrackElemType.halfLoopUp,
  TrackElemType.halfLoopDown,
  TrackElemType.leftCorkscrewUp,
  TrackElemType.rightCorkscrewUp,
  TrackElemType.leftCorkscrewDown,
  TrackElemType.rightCorkscrewDown,
  TrackElemType.leftBarrelRollUpToDown,
  TrackElemType.rightBarrelRollUpToDown,
  TrackElemType.leftBarrelRollDownToUp,
  TrackElemType.rightBarrelRollDownToUp,
  TrackElemType.leftLargeHalfLoopUp,
  TrackElemType.rightLargeHalfLoopUp,
  TrackElemType.leftLargeHalfLoopDown,
  TrackElemType.rightLargeHalfLoopDown,
  TrackElemType.leftLargeCorkscrewUp,
  TrackElemType.rightLargeCorkscrewUp,
  TrackElemType.leftLargeCorkscrewDown,
  TrackElemType.rightLargeCorkscrewDown,
  TrackElemType.leftMediumHalfLoopUp,
  TrackElemType.rightMediumHalfLoopUp,
  TrackElemType.leftMediumHalfLoopDown,
  TrackElemType.rightMediumHalfLoopDown,
  TrackElemType.leftZeroGRollUp,
  TrackElemType.rightZeroGRollUp,
  TrackElemType.leftZeroGRollDown,
  TrackElemType.rightZeroGRollDown,
  TrackElemType.leftLargeZeroGRollUp,
  TrackElemType.rightLargeZeroGRollUp,
  TrackElemType.leftLargeZeroGRollDown,
  TrackElemType.rightLargeZeroGRollDown,
  TrackElemType.multiDimInvertedFlatToDown90QuarterLoop,
  TrackElemType.up90ToInvertedFlatQuarterLoop,
  TrackElemType.invertedFlatToDown90QuarterLoop,
  TrackElemType.leftEighthDiveLoopUpToOrthogonal,
  TrackElemType.rightEighthDiveLoopUpToOrthogonal,
  TrackElemType.leftEighthDiveLoopDownToDiag,
  TrackElemType.rightEighthDiveLoopDownToDiag
]);
